
/*
 * MazeRunner.java
 *
 */
package mazerunner;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.Timer;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

public class MazeRunner extends javax.swing.JFrame {
// Add instance variables here

    public static final int wall = 0;
    public static final int open = 1;
    public static final int visited = 2;
    public static final int onpath = 3;
    public static final int start = 4;
    public static final int end = 5;
    public static final int pending = 6;
    public static final int mazeSize = 50;
    JFileChooser fileChooser = new JFileChooser();
    public int maze[][] = new int[mazeSize][mazeSize];
    public boolean running = false;
    public boolean searching = true;
    public Collection points;
    public Color colors[] = {Color.BLACK, Color.WHITE, Color.ORANGE, Color.RED, Color.BLUE, Color.YELLOW, Color.MAGENTA};
    public Point k;
    public int counter = 0;

    public Timer clock = new Timer(100, new ActionListener() {

        public void actionPerformed(ActionEvent e) {
            tick();
            mazePanel.repaint();
        }
    });

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MazeRunner().setVisible(true);
            }
        });
    }

    public class MyPanel extends JPanel {

        @Override
        public void paint(Graphics g) {
            super.paint(g);

            for (int i = 0; i < mazeSize; i++) {
                for (int j = 0; j < mazeSize; j++) {
                    g.setColor(colors[maze[i][j]]);
                    g.fillRect(j * 12, i * 12, 12, 12);
                }
            }
        }
    }

    public void tick() {

        if (running) {
            if (searching) {
                if (!points.isEmpty()) {
                    k = points.get();
                    findPoints(k.x, k.y + 1, k);
                    findPoints(k.x, k.y - 1, k);
                    findPoints(k.x - 1, k.y, k);
                    findPoints(k.x + 1, k.y, k);
                }
                repaint();
            } else {
                maze[k.x][k.y] = onpath;
                if (k.previousPoint != null) {
                    k = k.previousPoint;
                    counter++;
                    jLabel1.setText("Counter " + counter);
                } else {
                    running = false;
                }
            }

        }
        // This is the main logic - if there is a maze loaded and it hasn't been solved yet, move to
        // the next square.
    }

    public void findPoints(int i, int j, Point p) {
        if (maze[p.x][p.y] != start) {
            maze[p.x][p.y] = visited;
        }
        if (maze[i][j] == end) {
            searching = false;
            k = p;
        }
        if (maze[i][j] == open) {
            points.add(new Point(i, j, p));
            maze[i][j] = pending;
        }

    }

    /**
     * Creates new form MazeRunner
     */
    public MazeRunner() {
        initComponents();
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mazePanel = new MyPanel();
        loadMaze = new javax.swing.JButton();
        collectionSelection = new javax.swing.JComboBox();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mazePanel.setBackground(new java.awt.Color(204, 255, 204));
        mazePanel.setPreferredSize(new java.awt.Dimension(600, 600));

        org.jdesktop.layout.GroupLayout mazePanelLayout = new org.jdesktop.layout.GroupLayout(mazePanel);
        mazePanel.setLayout(mazePanelLayout);
        mazePanelLayout.setHorizontalGroup(
            mazePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 600, Short.MAX_VALUE)
        );
        mazePanelLayout.setVerticalGroup(
            mazePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 600, Short.MAX_VALUE)
        );

        loadMaze.setText("Load File");
        loadMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMazeActionPerformed(evt);
            }
        });

        collectionSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stack", "Queue" }));

        title.setText("No File Loaded");

        jLabel1.setText("Counter");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(mazePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(loadMaze, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(46, 46, 46))
                    .add(layout.createSequentialGroup()
                        .add(collectionSelection, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(loadMaze)
                        .add(81, 81, 81)
                        .add(collectionSelection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(mazePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadMazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMazeActionPerformed
        int retval = fileChooser.showOpenDialog(this);
        if (retval == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                if (collectionSelection.getSelectedIndex() == 0) {
                    points = new Stack();
                } else {
                    points = new Queue();
                }
                BufferedReader reader = new BufferedReader(new FileReader(file));
                String s;
                int row = 0;
                while ((s = reader.readLine()) != null) {

                    for (int i = 0; i < s.length(); i++) {

                        if (s.charAt(i) == '*') {
                            maze[row][i] = wall;
                        } else if (s.charAt(i) == ' ') {
                            maze[row][i] = open;
                        } else if (s.charAt(i) == 'S') {
                            maze[row][i] = start;
                            points.add(new Point(row, i));
                        } else if (s.charAt(i) == 'F') {
                            maze[row][i] = end;
                        }

                    }
                    row++;
                    System.out.println(row);
// Place code here to take each string from the file and use it to initialize the maze.
// * = wall
// space = empty
// S = start location
// F = finish location
                }
                running = true;
                searching = true;
                counter = 0;
            } catch (Exception e) {
                title.setText("File Error");
            }
    }//GEN-LAST:event_loadMazeActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox collectionSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadMaze;
    private javax.swing.JPanel mazePanel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
